/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotionRouteImport } from './routes/notion'
import { Route as ArticlesRouteImport } from './routes/articles'

const NotionRoute = NotionRouteImport.update({
  id: '/notion',
  path: '/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/articles': typeof ArticlesRoute
  '/notion': typeof NotionRoute
}
export interface FileRoutesByTo {
  '/articles': typeof ArticlesRoute
  '/notion': typeof NotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/articles': typeof ArticlesRoute
  '/notion': typeof NotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/articles' | '/notion'
  fileRoutesByTo: FileRoutesByTo
  to: '/articles' | '/notion'
  id: '__root__' | '/articles' | '/notion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ArticlesRoute: typeof ArticlesRoute
  NotionRoute: typeof NotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notion': {
      id: '/notion'
      path: '/notion'
      fullPath: '/notion'
      preLoaderRoute: typeof NotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ArticlesRoute: ArticlesRoute,
  NotionRoute: NotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
